### ISSUE TITLE
Enumerar exemplos de cada funcionalidade da ferramenta

### ISSUE THREAD

**Issue by brunovani** [terraembytes/ISMRQueryToolManual#1]
Para o manual ficar mais acessível, criar numeração para os exemplos e figuras.
Ex: "1. Plot"; "Figure 1.1 - captions for the figure".

Também precisaremos corrigir alguns exemplos. Poderia enumerar todos os exemplos para ficar mais fácil de indicar as correções necessárias?

**Comment by Braiao** [comment]
Acabei de fazer o commit da versão atualizada, a versão antiga está nas tags como 'v1.0'
